/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * TechCenter.Api | v1 - version 1.0.0
 *
 *
 *
 * OpenAPI version: 3.0.1
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'Auth.register': ['POST', '/api/auth/register'],
  'Auth.login': ['POST', '/api/auth/login'],
  'Auth.refreshToken': ['POST', '/api/auth/refresh'],
  'Auth.logout': ['POST', '/api/auth/logout'],
  'techCenterApi.post_api_user_basic_info': ['POST', '/api/user/basicInfo'],
  'techCenterApi.post_api_file_resources_upload': ['POST', '/api/fileResources/upload'],
  'techCenterApi.get': ['GET', '/'],
  'techCenterApi.post_api_content_posts_get_by_id': ['POST', '/api/content/posts/getById'],
  'techCenterApi.post_api_content_videos_get_by_id': ['POST', '/api/content/videos/getById'],
  'techCenterApi.post_api_content_posts_add': ['POST', '/api/content/posts/add'],
  'techCenterApi.post_api_content_videos_add': ['POST', '/api/content/videos/add'],
  'techCenterApi.post_api_content_posts_update': ['POST', '/api/content/posts/update'],
  'techCenterApi.post_api_content_videos_update': ['POST', '/api/content/videos/update'],
  'techCenterApi.post_api_content_posts_delete': ['POST', '/api/content/posts/delete'],
  'techCenterApi.post_api_content_videos_delete': ['POST', '/api/content/videos/delete']
}
