/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * TechCenter.Api | v1 - version 1.0.0
 *
 *
 *
 * OpenAPI version: 3.0.1
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'Auth.Register': ['POST', '/api/auth/register'],
  'Auth.Login': ['POST', '/api/auth/login'],
  'Auth.RefreshToken': ['POST', '/api/auth/refresh'],
  'Auth.Logout': ['POST', '/api/auth/logout'],
  'User.GetUserBasicInfo': ['POST', '/api/user/basicInfo'],
  'Content.QueryPostsForManage': ['POST', '/api/content/posts/queryForManage'],
  'Content.QueryVideosForManage': ['POST', '/api/content/videos/queryForManage'],
  'Content.GetPostByIdForManage': ['POST', '/api/content/posts/getByIdForManage'],
  'Content.GetVideoByIdForManage': ['POST', '/api/content/videos/getByIdForManage'],
  'Content.QueryPostsForViewer': ['POST', '/api/content/posts/queryForViewer'],
  'Content.QueryVideosForViewer': ['POST', '/api/content/videos/queryForViewer'],
  'Content.GetPostById': ['POST', '/api/content/posts/getById'],
  'Content.GetVideoById': ['POST', '/api/content/videos/getById'],
  'Content.post_api_content_posts_add': ['POST', '/api/content/posts/add'],
  'Content.post_api_content_videos_add': ['POST', '/api/content/videos/add'],
  'Content.post_api_content_posts_update': ['POST', '/api/content/posts/update'],
  'Content.post_api_content_videos_update': ['POST', '/api/content/videos/update'],
  'Content.post_api_content_posts_delete': ['POST', '/api/content/posts/delete'],
  'Content.post_api_content_videos_delete': ['POST', '/api/content/videos/delete'],
  'BuiltinStorageProvider.UploadFile': ['POST', '/api/builtinStorageProvider/upload'],
  'techCenterApi.get': ['GET', '/']
}
